### ISSUE TITLE
Create Desktop Hero Header

### ISSUE THREAD

**Issue by thmscly** [CD-Squared-Tech/cd-squared-tech#20]
![Screenshot (111)](https://github.com/CD-Squared-Tech/cd-squared-tech/assets/29210776/5a993901-4354-4cdc-b051-a881f4a3e916)
- [ ] Fit entire width of viewport
- [ ] Fit 75% of view height
- [ ] Background image specified in wireframe (reach out to @WonderboyPark for file)
- [ ] Add overlay to background image
- [ ] Add H1
- [ ] Style h1
- [ ] Add sub-header
- [ ] Style sub-header
- [ ] Add button
- [ ] Hyperlink button
- [ ] Style button

**Comment by WonderboyPark** [comment]
I can work on this. do we have the main structure for the page created? main wrapper, side bar nav, main content for different sections?
