### ISSUE TITLE
Create Contribution Guidelines

### ISSUE THREAD

**Issue by thmscly** [CD-Squared-Tech/cd-squared-tech#21]
Create contributionGuidelines.md file with clear guidelines for contributing to the repo

An example: https://gist.github.com/briandk/3d2e8b3ec8daf5a27a62#file-contributing-md

Find concepts that don't have value in our project and delete them.

Edit concepts to our purpose.

**Comment by mblackonline** [comment]
@thmscly @shimekukuri - I've submitted a pull request with the initial draft of the CONTRIBUTING.md document. I don't have access to our repo Settings, so I did not add the issues and feature request templates. Also, I believe that a Discord Admin will need to create a permanent link for the invite, as I could only create a 7-day invite link.

I can help with the README.md too unless someone else is working on it.  Just let me know!

**Comment by mblackonline** [comment]
Note - I have created a README.md and submitted an updated PR with it and the CONTRIBUTING.md together.

**Comment by mblackonline** [comment]
@shimekukuri @thmscly 

Hi Team - Now that we've finished the initial drafts for the README and CONTRIBUTING files, can we please close this issue?

I know that more revisions are needed on the drafts, and I have some ideas for improvements. I think it would be good to create new issues for those suggestions. That way, it will be easier to track and manage the revisions. 

What do you think?

Thanks,
Matt
