### ISSUE TITLE
Create Desktop Sidebar

### ISSUE THREAD

**Issue by thmscly** [CD-Squared-Tech/cd-squared-tech#26]
![cdtech-sidebar](https://github.com/CD-Squared-Tech/cd-squared-tech/assets/29210776/78796cfa-cf0a-4608-bb5b-d52e8f2e560a)

The Sidebar has these components:

### Components:
- [ ] Logo
    - [ ] Centered
    - [ ] Some top-margin
- [ ] Social Media Links
    - [ ] Determine where to get icons from
    - [ ] LinkedIn
        - [ ] https://www.linkedin.com/groups/14283167/ 
    - [ ] Discord
        - Still debating how to implement Discord (don't want strangers constantly joining)
    - [ ] Facebook
        - Doesn't exist yet 
    - [ ] Color: #678693
- [ ] Copyright
    - [ ] Stuck to bottom
    - [ ] Slight margin-bottom

### Properties of Sidebar:
- [x] Fixed position
- [ ] Top-most component on screen (closest to your face)
- [x] Background color: #F5FAFC
- [x] Approx 10% of screen width
- [x] 100% page height

**Comment by thmscly** [comment]
@CD-Squared-Tech/front-end

**Comment by WonderboyPark** [comment]
who ever decides to work on this... let me know if you need me to get svg's for the icons... stacked svg logo is already uploaded... i will provide horizontal svg logo for mobile view

**Comment by WonderboyPark** [comment]
@natashaillum i submitted PR today that gives the sidebar height on mobile a css variable. this can be updated depending on the layout. 

also here is the svg file for the horizontal logo on mobile
![logo-horizontal](https://github.com/CD-Squared-Tech/cd-squared-tech/assets/2857387/b93f95b4-b31c-4d5b-83b8-5cf02a0ff65f)

**Comment by chrisciampoli** [comment]
This look to be completed?

**Comment by mblackonline** [comment]
Desktop Sidebar created. Issue closed.
