### ISSUE TITLE
Create 50/50 section with image right, heading and text on left

### ISSUE THREAD

**Issue by WonderboyPark** [CD-Squared-Tech/cd-squared-tech#40]
Create second 50/50 section just under cards section
- [ ] Create 50/50 layout
- [ ] Image on right, 16:9 ratio
- [ ] Left side Heading
- [ ] Left side Text
- [ ] Collapsible for mobile devices

**Comment by WonderboyPark** [comment]
@Rae1821 @Coltensiemer You guys work out who wants to do which 50/50 section. There are two of them.

**Comment by SilvaMedal** [comment]
Completed.
