### ISSUE TITLE
Create Contact From

### ISSUE THREAD

**Issue by WonderboyPark** [CD-Squared-Tech/cd-squared-tech#41]
Create contact form as final section on page

- [ ] Create section for contact form
- [ ] create field for first name
- [ ] create field for last name
- [ ] create field for email address
- [ ] create field for message
- [ ] add submit button
- [ ] form should be about middle 50% width centered on desktop
- [ ] form should be 100% view centered on mobile

**Comment by smyoungblood** [comment]
James- I'm going to work on this section. Can you assign me to this issue please?

**Comment by SilvaMedal** [comment]
Form looks complete.
