### ISSUE TITLE
Help us choose a tech stack/backend for our website as we advance. Your feedback is needed!

### ISSUE THREAD

**Issue by mblackonline** [CD-Squared-Tech/cd-squared-tech#43]
@CD-Squared-Tech/back-end @CD-Squared-Tech/ops @CD-Squared-Tech/front-end @CD-Squared-Tech/cybersecurity @CD-Squared-Tech/project-management @CD-Squared-Tech/design 
* *Input from everyone is appreciated, whether you're on one of the above teams or not!*

### Considerations:
- Cost-effectiveness: Seek options that minimize development and maintenance costs.
- Scalability: Plan for handling potential growth and increased traffic.
- Maintenance: Opt for technologies with strong community support and regular updates.
- Security: Ensure the chosen technologies prioritize security measures.
- Team Collaboration: Leverage our team's strengths to facilitate collaboration and encourage participation.
- Performance: Evaluate options to ensure good performance and optimize the user experience.
- Integration: Consider how well the backend integrates with other technologies and services for seamless workflows.
- Community and Support: Seek to use technologies with active communities that offer resources and support.

### How to Participate:
Add a comment below to provide your input and insights. We'll collect everyone's suggestions and opinions, and as a team, we'll conduct a voting poll on Discord to finalize our decision.

Thank you all for your valuable input! 🙌

**Comment by jus10mar10** [comment]
Here is my Django pitch...

- Django is an open source and free web framework. Django has a "batteries included" approach including an ORM, Authentication, Admin page, security, and templating. This will make getting started much simpler.

- Some popular high-traffic applications using Django are Spotify, Instagram, YouTube, Pinterest, Mozilla, and more ([link](https://djangostars.com/blog/10-popular-sites-made-on-django/))

- Django has daily developer activity updating and maintaining the project. It is among the most popular web frameworks ([link](https://www.statista.com/statistics/1124699/worldwide-developer-survey-most-used-frameworks-web/))

- One of Django’s key features is its built-in security mechanisms. It assists in preventing common security mistakes like SQL injection, CSRF attacks, and XSS attacks.

- Django's modular design will make team collaboration easier. This means changes should require a massive overhaul.

- Has built-in tools to optimize database queries. Performance can be enhanced through caching. ([link](https://earthly.dev/blog/improve-django-performance-caching/))

- Django has a wide variety of integration available through open source extensions and the ability to use popular front-end languages inside the framework (React, Vue.js, etc), CDNs, CI/CD pipelines, containerization, etc

- As mentioned there is a huge amount of open source extensions to the Django framework that provide additional solutions on top of the base framework. [Examples](https://learndjango.com/tutorials/10-most-used-django-packages)

Cons (I stole this list):
- Django’s robustness can introduce performance overhead, especially for small-scale projects. The framework’s full-featured nature might lead to unnecessary processing and slow down response times in certain scenarios.

- For newcomers to web development, Django’s learning curve can be quite steep. Its extensive features and complex architecture may overwhelm beginners, requiring more time and effort to grasp.

- Django follows a monolithic architecture, meaning that all components are tightly integrated. This can be a limitation when developers want to use specific modules or features without adopting the entire framework.

- Although Django can handle moderate traffic and loads, it may face challenges with scaling for high-traffic websites. Scaling Django apps to accommodate rapid growth can demand significant optimizations.

- While convenient for standard use cases, Django’s ORM (Object-Relational Mapping) can become restrictive for complex database operations or legacy database systems.

- Django primarily focuses on backend development, which sometimes means less flexibility in front end. While it supports frontend technologies, developers might find more flexibility and freedom with specialized frontend frameworks.

Link: [What is Django (IBM)](https://www.ibm.com/topics/django)

**Comment by mblackonline** [comment]
@jus10mar10 Thanks for sharing the Django information! The links and resources you provided are helpful for exploring this option further.

I'm curious if anyone in our organization has experience using Django in production. It would be great to hear about their experiences and insights. 

I've done a little research on potential hosting options and came across [PythonAnywhere by Anaconda](https://www.pythonanywhere.com/pricing/). They offer affordable paid plans as well as a free tier to get started. If the group decides to go with Django, this might be a hosting option worth considering.

**Comment by mblackonline** [comment]
I am closing this issue, as a decision has been reached to use Django for now. We will not conduct a vote. Communication with the team leads has been conducted to ensure everyone is on the same page with the project plan.
